# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1
    - run: npm install @vue/cli@latest
    - name: Run build task...
      run: npm run build
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: {{ghname}}
        author_email: {{ghemail}}
        message: 'deploy'
        branch: gh-pages
        add: './dist'